### ISSUE TITLE
Simple commands helps

### ISSUE THREAD

**Issue by TJ-Solimut** [chunliu/outlook-markdown#10]
Hello, thanks a lot for your work,

I struggle to use simple commands, that seems to be not working :

![image](https://user-images.githubusercontent.com/131142719/232705990-a433b5e5-2c13-4360-9730-a5fa327dd860.png)

Am I missing something here ?

**Comment by chunliu** [comment]
I cannot reproduce it on my side. The collapsible content seems working fine in preview. 

![image](https://user-images.githubusercontent.com/2128551/233785771-bf7ae5ae-f814-4ac9-9a9e-e59c1baa3f42.png)

But it doesn't work when you insert it to the email body. I guess the Outlook editor doesn't support collapsible content.

**Comment by TJ-Solimut** [comment]
Well, thanks for having a look !
