### ISSUE TITLE
Not add-ins import online for outlook 2013

### ISSUE THREAD

**Issue by oleotiger** [chunliu/outlook-markdown#2]
I'm using outlook 2013 but I didn't find a way how to import add-ins online with an url.

I only find a way to import add-ins locally though *.exe or *.dll.

Is there any way that I can use outlook-markdown though importing locally?

**Comment by chunliu** [comment]
It should work with Outlook 2013. Have you followed the instruction in this document? https://docs.microsoft.com/en-us/office/dev/add-ins/outlook/sideload-outlook-add-ins-for-testing#outlook-2013

**Comment by oleotiger** [comment]
Yes. The outlook version is 2013 but I think it's modified or customized by my organization. I cannot go forward following the instruction in the document mentioned above.

**Comment by oleotiger** [comment]
So I wonder how could I import this add-in locally?

**Comment by chunliu** [comment]
I am afraid you cannot import it locally as the add-in needs to be deployed to a web server. You can check with your Exchange administrators if they can grant you `My Custom Apps` role. See this document for details: https://docs.microsoft.com/en-us/office/dev/add-ins/outlook/testing-and-tips#sideload-the-add-in
