### ISSUE TITLE
add a bit more line spacing to prevent text/code block overlapping

### ISSUE THREAD

**Issue by charltonstanley** [chunliu/outlook-markdown#7]
First off, this is an awesome extension thank you so much for making it!

Secondly, this may be an issue on my end, but I noticed that some of the inline code blocks start to creep into the text of the second line. In my screenshot you can see that the inline code block in the first line is overlapping the `d` in `code` and obscuring the `i` in `snippets` in the second line. Is there something that can be done to adjust the spacing a little bit?

thanks! 

(you might have to click on the image to see it in full-size).
![Selection_191](https://user-images.githubusercontent.com/22397984/162834708-7326cd07-512e-4b62-8f94-266a0608ce93.png)

**Comment by chunliu** [comment]
From the inline style, I guess you are using new Outlook or Outlook online. I cannot seem to reproduce the issue at my end. But the line space in your screenshot seems tighter than mine. Are you on Windows or Mac? new Outlook app or a browser? If you are using a browser, which browser is it? 

![image](https://user-images.githubusercontent.com/2128551/162862085-a9439480-f6f0-4495-94d3-a6975cab4589.png)

The line space is controlled by Outlook. There is no styling in the html converted from the markdown which could influence it. And in the new Outlook or Outlook online, not like in the old Outlook desktop version, I could not even find the option to configure the line space. 

I don't there is anything that can be done from the add-in perspective to help you address the issue.

**Comment by charltonstanley** [comment]
I'm on Linux Mint 20.03, using Brave Browser (chromium based). As for outlook, i'm using the [new outlook web](https://docs.microsoft.com/en-us/office/dev/add-ins/outlook/sideload-outlook-add-ins-for-testing?tabs=windows#new-outlook-on-the-web).

I appreciate you looking into it. Feel free to close this if you think there is nothing else that can be done.

Thank you!

**Comment by chunliu** [comment]
It might be a rendering or compatibility issue of Outlook web itself.
